### ISSUE TITLE
关于获取标注后的bitmap为空

### ISSUE THREAD

**Issue by songjiejoy** [SirLYC/ImageLabelView#2]
在demo最后获取标注的bitmap的时候，您使用的代码是label.getDrawingCache()，我这边获取到的结果是null,我也尝试了网上各种view转bitmap的方法获取的都是null,您的demo获取的也是null,我用的图片分辨率都是2000*3000以上分辨率的，不知道是什么问题引起的，想请您帮忙排查一下问题，看看如何获取标注过的bitmap.

**Comment by SirLYC** [comment]
可以试一下包装`Bitmap`到`Canvas`，然后手动调用`View.draw`。
